#!/usr/bin/env ruby 

require 'rubygems'
require 'twitter'
require 'grit'
include Grit


src_dir = ARGV[0]
branch = "origin/stable"
YOUR_CONSUMER_KEY = "key........"
YOUR_CONSUMER_SECRET = "secret......"
YOUR_OAUTH_TOKEN = "token......"
YOUR_OAUTH_TOKEN_SECRET = "tokent_secret....."

history_limit = 20 # 200 max

repo = Repo.new(src_dir)

Twitter.configure do |config|
  config.consumer_key = YOUR_CONSUMER_KEY
  config.consumer_secret = YOUR_CONSUMER_SECRET
  config.oauth_token = YOUR_OAUTH_TOKEN
  config.oauth_token_secret = YOUR_OAUTH_TOKEN_SECRET
end

timeline = Twitter.home_timeline(:count => history_limit)

last_sha = ""
# first find the most recent commit message
timeline.each do |message|
  if matchdata = message.text.match(/^(\w{7}) /)
    last_sha = matchdata[1]
    break
  end
end

puts "last sha found on twitter: #{last_sha}"


new_commits = []
repo.commits(branch, history_limit).each do |commit|
  break if commit.id_abbrev == last_sha
  new_commits << commit
end

# oldest newest update first
new_commits.reverse.each do |commit|

  unless commit.message.match(/^Merge /)
    mesg = commit.id_abbrev + " " + commit.message[0,150].sub(/\n.*/m,"")
    if commit.message.size > 150
      mesg += "..."
    end
    puts "posting: #{mesg}"

    Twitter.update(mesg)
    sleep 1
  end

end
